openapi: 3.0.3
info:
  title: Toastmasters Web API
  version: 1.0.0
  description: API documentation for Toastmasters Web application
paths:
  /api/users/me/{id}/:
    get:
      operationId: users_me_retrieve
      description: 使用者可以查看或更新自己的個人資料
      summary: 取得或更新使用者資料
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - User Profile
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
        '404':
          description: 找不到使用者
    put:
      operationId: users_me_update
      description: 使用者可以查看或更新自己的個人資料
      summary: 取得或更新使用者資料
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - User Profile
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
        '404':
          description: 找不到使用者
components:
  schemas:
    Club:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        location:
          type: string
          nullable: true
          maxLength: 255
        meeting_time:
          type: string
          nullable: true
          maxLength: 50
        description:
          type: string
          nullable: true
      required:
      - id
      - name
    Login:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          writeOnly: true
      required:
      - password
      - username
    Logout:
      type: object
      properties:
        refresh:
          type: string
      required:
      - refresh
    Register:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
          writeOnly: true
        display_name:
          type: string
      required:
      - display_name
      - email
      - password
      - username
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        display_name:
          type: string
          nullable: true
          maxLength: 100
      required:
      - id
      - username
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
