# Generated by Django 5.2.4 on 2025-08-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_delete_memberships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='meeting_time',
        ),
        migrations.AddField(
            model_name='clubs',
            name='meeting_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='meeting_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='meeting_time_display',
            field=models.CharField(blank=True, help_text='顯示用的時間描述', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='meeting_weekday',
            field=models.IntegerField(blank=True, choices=[(0, '星期一'), (1, '星期二'), (2, '星期三'), (3, '星期四'), (4, '星期五'), (5, '星期六'), (6, '星期日')], null=True),
        ),
    ]
